# Generated by Django 3.0.4 on 2020-04-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phnumber', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
            ],
        ),
    ]
