# Generated by Django 3.0.4 on 2020-05-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardNumber', models.IntegerField()),
                ('NameInCard', models.CharField(max_length=30)),
                ('CVV', models.IntegerField()),
                ('MM', models.IntegerField()),
                ('YY', models.IntegerField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
