# Generated by Django 3.0.4 on 2020-05-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='CreditCard',
            field=models.BooleanField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='DebitCard',
            field=models.BooleanField(default=''),
            preserve_default=False,
        ),
    ]
