# Generated by Django 3.0.4 on 2020-06-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200514_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='CreditCard',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='DebitCard',
        ),
    ]
