# Generated by Django 3.0.4 on 2020-04-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('t_id', models.IntegerField()),
                ('s_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('no_of_seats', models.IntegerField()),
            ],
        ),
    ]
