# Generated by Django 3.0.4 on 2020-04-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking_tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('ticket_id', models.IntegerField()),
                ('match_name', models.CharField(max_length=100)),
                ('no_of_tickets', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
    ]
