# Generated by Django 3.0.4 on 2020-04-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_tickets',
            name='match_date',
            field=models.DateField(default='2020-12-12'),
            preserve_default=False,
        ),
    ]
