# Generated by Django 3.0.4 on 2020-04-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_tickets_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_tickets',
            name='match_date',
            field=models.DateField(default='2020/12/20'),
        ),
    ]
