# Generated by Django 3.0.4 on 2020-04-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20200430_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_tickets',
            name='match_date',
        ),
        migrations.AddField(
            model_name='booking_tickets',
            name='date',
            field=models.DateField(default=2020-12-10),
            preserve_default=False,
        ),
    ]
