# Generated by Django 3.0.4 on 2020-06-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_tickets_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_tickets',
            name='select_seats',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
