# Generated by Django 3.0.4 on 2020-06-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_tickets_select_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_tickets',
            name='select_seats',
            field=models.CharField(max_length=10),
        ),
    ]
